Feature/navigation component
isdi-coders-2023/PerezososCulturistas-202309-bcn pull request #13
Opened 2023-10-31 12:08 UTC by fjgrande

2023-10-31 12:09 UTC, adricruzado submitted a review, later dismissed

2023-10-31 12:25 UTC, adricruzado submitted a review, later dismissed

2023-10-31 13:24 UTC, patriciafemenias requested changes
remember, you cant write in uppercase, you will do it later in styles

2023-11-01 12:02 UTC, adricruzado approved these changes
We should check the order of the imports, good job Fran!

2023-11-01 12:02 UTC, patriciafemenias approved these changes
Guay! tan sólo checkea el orden de los imports!

2023-11-01 12:02 UTC, merged